### ISSUE TITLE
Hay Code Nai Arn Yark Jank Lay

### ISSUE THREAD

**Issue by TinnerKun** [boon4681/CloneMe#1]
**Chui Arn Hai Fung Noi**
![279656213_1004982186819512_6816619126071426317_n](https://user-images.githubusercontent.com/45807795/173197973-438aa76c-4ed3-41f9-be28-46c3405c7fa3.jpg)

**Comment by boon4681** [comment]
สวัสดี อ่านยากหรอ เอาชาเขียว หรือ กาแฟดำดี


> **Chui Arn Hai Fung Noi** ![279656213_1004982186819512_6816619126071426317_n](https://user-images.githubusercontent.com/45807795/173197973-438aa76c-4ed3-41f9-be28-46c3405c7fa3.jpg)

**Comment by XyZerKunG** [comment]
ชาเขียวครับ ไม่ใส่ชา 🦄

**Comment by boon4681** [comment]
> ชาเขียวครับ ไม่ใส่ชา 🦄

ห้าสิบบาท แต่ไปลอง numbaht ด้วย

**Comment by AconomicX** [comment]
แพงจุงเลย

> **Chui Arn Hai Fung Noi** ![279656213_1004982186819512_6816619126071426317_n](https://user-images.githubusercontent.com/45807795/173197973-438aa76c-4ed3-41f9-be28-46c3405c7fa3.jpg)

**Comment by TinnerKun** [comment]
> > ชาเขียวครับ ไม่ใส่ชา 🦄
> 
> ห้าสิบบาท แต่ไปลอง numbaht ด้วย

ห้ะ กี่บาทนะ

**Comment by XyZerKunG** [comment]
ห้าบาทถ้วน พอดีมัน bug ไม่นับ 0

**Comment by boon4681** [comment]
งั้นไม่ขายปิดเลยละกัน
